#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# shit os 2 -- build dash against our libc.
#
# dash is the proof that the job control layer is real. Our own sh was written
# against this kernel and proves nothing about it; dash was written against
# Unix in 1997 and does not know or care what it is running on. If process
# groups, terminal ownership and stop signals work for dash, they work.
#
# Not vendored: downloaded, checksummed and built here, so 20,000 lines of
# somebody else's BSD-licensed source stay out of a GPLv3 tree.
#
# Not patched either. The whole configuration is ports/dash/config.h, written
# by hand instead of run through autoconf -- cross-compiling autoconf means
# running probes and then overriding them, and every answer here is one we
# already know. If dash needed a source change, that would be a bug report
# about our libc; so far it has needed a dozen additions to it and no patches.
#
# usage: build.sh <output directory>

set -eu

VERSION="0.5.12"
ARCHIVE="dash-${VERSION}.tar.gz"
URL="http://gondor.apana.org.au/~herbert/dash/files/${ARCHIVE}"
SHA256="6a474ac46e8b0b32916c4c60df694c82058d3297d8b385b74508030ca4a8f28a"

OUTPUT_DIR="${1:?usage: build.sh <output directory>}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

CLANG="${SHITOS_CLANG:-clang}"
# The generators below run on this machine, not the target, so they need a
# compiler for this machine.
HOST_CC="${SHITOS_HOST_CC:-cc}"
CACHE="${SHITOS_PORT_CACHE:-$ROOT/.port-cache}"
mkdir -p "$CACHE" "$OUTPUT_DIR"

# --- fetch ---------------------------------------------------------------

if [ ! -f "$CACHE/$ARCHIVE" ]; then
    echo "dash: downloading $URL"
    curl -sSfL "$URL" -o "$CACHE/$ARCHIVE.partial"
    mv "$CACHE/$ARCHIVE.partial" "$CACHE/$ARCHIVE"
fi

ACTUAL="$(sha256sum "$CACHE/$ARCHIVE" | cut -d' ' -f1)"
if [ "$ACTUAL" != "$SHA256" ]; then
    echo "dash: checksum mismatch for $ARCHIVE" >&2
    echo "  expected $SHA256" >&2
    echo "  got      $ACTUAL" >&2
    rm -f "$CACHE/$ARCHIVE"
    exit 1
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

tar xzf "$CACHE/$ARCHIVE" -C "$WORK"
SRC="$WORK/dash-${VERSION}/src"
CONFIG="$ROOT/ports/dash/config.h"

# --- generate ------------------------------------------------------------
#
# dash builds five small programs, runs them, and compiles what they print.
# They run here rather than on the target, so they are built with the host
# compiler against the host's headers -- the only one where that shows is
# mksignames, and signal numbers agree with Linux for everything we define.

HOST_FLAGS="-O1 -w -DBSD=1 -DSHELL -include $CONFIG -I$SRC"

( cd "$SRC" && sh mktokens )
"$HOST_CC" $HOST_FLAGS -o "$WORK/mksyntax" "$SRC/mksyntax.c"
( cd "$SRC" && "$WORK/mksyntax" )
"$HOST_CC" $HOST_FLAGS -o "$WORK/mknodes" "$SRC/mknodes.c"
( cd "$SRC" && "$WORK/mknodes" nodetypes nodes.c.pat )
# dash's own mksignames reads the *host's* signal.h, so it emits a table sized
# and named for Linux -- 65 entries, half of them signals we do not have. The
# excess initialisers are then silently dropped when the file is compiled
# against our 32-signal header, which happens to leave the entries dash reads
# correct and would stop doing so the moment either side moved. Writing the
# table here instead means it can only ever match shitos/abi/signal.h, and
# there is one fewer host program in the build.
{
    echo "/* Generated by ports/dash/build.sh from shitos/abi/signal.h. */"
    echo "#include <signal.h>"
    echo "const char *const signal_names[NSIG + 1] = {"
    # Index 0 is "EXIT", the trap name for the shell exiting rather than a
    # signal. The rest are our signal numbers, in order, with a decimal name
    # for each gap so no index is null.
    awk '
        BEGIN { for (i = 0; i < 33; ++i) names[i] = i }
        /^#define SIG[A-Z0-9]+ [0-9]+$/ {
            number = $3 + 0
            if (number < 33) { name = substr($2, 4); names[number] = name }
        }
        END {
            printf "    \"EXIT\",\n"
            for (i = 1; i < 32; ++i) printf "    \"%s\",\n", names[i]
            printf "    0\n"
        }
    ' "$ROOT/include/shitos/abi/signal.h"
    echo "};"
} > "$SRC/signames.c"
"$HOST_CC" -E -x c $HOST_FLAGS -o "$SRC/builtins.def" "$SRC/builtins.def.in"
( cd "$SRC" && sh mkbuiltins builtins.def )

# The sources, in the order dash's own Makefile lists them. histedit.c is left
# out: with SMALL its body is empty, and its includes are not.
SOURCES="alias arith_yacc arith_yylex cd error eval exec expand input jobs mail
         main memalloc miscbltin mystring options parser redir show trap output
         system var bltin/printf bltin/test bltin/times"

# mkinit reads every source and writes the init/reset code that ties them
# together, so it runs last.
"$HOST_CC" $HOST_FLAGS -o "$WORK/mkinit" "$SRC/mkinit.c"
# shellcheck disable=SC2086
( cd "$SRC" && "$WORK/mkinit" $(for name in $SOURCES; do printf '%s.c ' "$name"; done) )

# --- build ---------------------------------------------------------------

CFLAGS="--target=x86_64-elf -ffreestanding -nostdlibinc -std=gnu99 -O2 -w
        -fno-pic -fno-pie -mno-red-zone
        -DBSD=1 -DSHELL -include $CONFIG
        -I$ROOT/user/libc/include -I$ROOT/include -I$SRC"

for name in $SOURCES builtins init nodes signames syntax; do
    # shellcheck disable=SC2086
    "$CLANG" $CFLAGS -c "$SRC/$name.c" -o "$WORK/$(basename "$name").o"
done

"$CLANG" --target=x86_64-elf -nostdlib -static -fuse-ld=lld \
    -Wl,--build-id=none -Wl,-z,noexecstack -Wl,-z,max-page-size=0x1000 \
    -Wl,--image-base=0x400000 -Wl,-e,_start \
    "$WORK"/*.o "$SHITOS_LIBC" -o "$OUTPUT_DIR/dash"

echo "dash: built $(wc -c < "$OUTPUT_DIR/dash") bytes -> $OUTPUT_DIR/dash"
