#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# shit os 2 -- check the regex engine against the host's glibc.
#
# A regex engine is the kind of code that looks right and is not: what matters
# is hundreds of small interactions between dialects, anchors, greediness and
# capture rules, and no reasonable number of hand-written assertions covers it.
# The host has a reference implementation; the target does not. So the same
# corpus goes through both and every disagreement is reported.
#
# Same trick, and same reason, as tools/check-libm.sh.

set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

CC="${CC:-clang}"
OBJCOPY="${OBJCOPY:-llvm-objcopy}"

# Build our regex for the host against our own headers.
"$CC" -std=gnu99 -O1 -nostdlibinc \
    -I"$ROOT/user/libc/include" -I"$ROOT/include" \
    -c "$ROOT/user/libc/src/regex.c" -o "$WORK/ours.o"

"$OBJCOPY" --prefix-symbols=shitos_ "$WORK/ours.o" "$WORK/ours-prefixed.o"

# Our regex.h, with the names the prefixing produced, so the test can talk
# about both implementations in one translation unit.
{
    echo '/* Generated by tools/check-regex.sh. */'
    echo '#ifndef SHITOS_REGEX_SHIM_H'
    echo '#define SHITOS_REGEX_SHIM_H'
    echo '#include <stddef.h>'
    sed -e 's/\bregex_t\b/shitos_regex_t/g' \
        -e 's/\bregmatch_t\b/shitos_regmatch_t/g' \
        -e 's/\bregoff_t\b/shitos_regoff_t/g' \
        -e 's/\bregcomp\b/shitos_regcomp/g' \
        -e 's/\bregexec\b/shitos_regexec/g' \
        -e 's/\bregerror\b/shitos_regerror/g' \
        -e 's/\bregfree\b/shitos_regfree/g' \
        -e 's/#define REG_/#define SHITOS_REG_/g' \
        -e '/#ifndef _REGEX_H/d' -e '/#define _REGEX_H/d' -e '/#endif \/\* _REGEX_H \*\//d' \
        -e '/#include <stddef.h>/d' \
        "$ROOT/user/libc/include/regex.h"
    echo '#endif'
} > "$WORK/shitos-regex.h"

# What our regex.c calls out to, under the prefixed names.
cat > "$WORK/host-stubs.c" <<'STUBS'
#include <ctype.h>
#include <stdlib.h>
#include <string.h>

void* shitos_malloc(size_t size) { return malloc(size); }
void* shitos_calloc(size_t count, size_t size) { return calloc(count, size); }
void* shitos_realloc(void* p, size_t size) { return realloc(p, size); }
void shitos_free(void* p) { free(p); }
void* shitos_memcpy(void* d, const void* s, size_t n) { return memcpy(d, s, n); }
int shitos_memcmp(const void* a, const void* b, size_t n) { return memcmp(a, b, n); }
size_t shitos_strlen(const char* s) { return strlen(s); }
void* shitos_memset(void* d, int c, size_t n) { return memset(d, c, n); }
/* clang lowers a small memcmp against zero to bcmp. */
int shitos_bcmp(const void* a, const void* b, size_t n) { return memcmp(a, b, n); }
STUBS

"$CC" -std=gnu99 -O1 -c "$WORK/host-stubs.c" -o "$WORK/host-stubs.o"
"$CC" -std=gnu99 -O1 -I"$WORK" "$ROOT/user/libc/test/regexcheck.c" \
    "$WORK/ours-prefixed.o" "$WORK/host-stubs.o" -o "$WORK/regexcheck"

exec "$WORK/regexcheck"
