import gzip, struct, sys

src = "/usr/share/consolefonts/Lat15-Terminus16.psf.gz"
data = gzip.open(src, "rb").read()

if data[:4] == b"\x72\xb5\x4a\x86":
    magic, ver, hdrsz, flags, length, charsize, height, width = struct.unpack("<8I", data[:32])
    glyphs = data[hdrsz:hdrsz + length * charsize]
    fmt = "PSF2"
elif data[:2] == b"\x36\x04":
    mode, charsize = data[2], data[3]
    length = 512 if (mode & 1) else 256
    width, height, hdrsz = 8, charsize, 4
    glyphs = data[hdrsz:hdrsz + length * charsize]
    fmt = "PSF1"
else:
    sys.exit("unknown psf magic %r" % data[:4])

print(f"{fmt}: {width}x{height}, {length} glyphs, charsize={charsize}", file=sys.stderr)
assert width == 8 and height == 16 and charsize == 16, "want an 8x16 font"

# Take the first 128 glyphs: for Lat15 the low 128 are ASCII in codepage order.
N = 128
out = []
out.append("""// SPDX-License-Identifier: GPL-3.0-or-later
// shit os 2 -- 8x16 console font
//
// Glyph data generated by tools/genfont.py from Terminus (Lat15-Terminus16.psf),
// which is distributed under the SIL Open Font License 1.1. See docs/third-party.md.
//
// Each glyph is 16 rows of 8 pixels, one byte per row, MSB = leftmost pixel.

#pragma once

#include <shitos/types.h>

namespace kernel::dev {

inline constexpr u32 FONT_WIDTH = 8;
inline constexpr u32 FONT_HEIGHT = 16;
inline constexpr u32 FONT_GLYPHS = 128;

inline constexpr u8 FONT_8X16[FONT_GLYPHS][FONT_HEIGHT] = {""")
for c in range(N):
    g = glyphs[c * charsize:(c + 1) * charsize]
    row = ", ".join("0x%02x" % b for b in g)
    ch = chr(c) if 32 <= c < 127 else ""
    label = f"  // 0x{c:02x} '{ch}'" if ch else f"  // 0x{c:02x}"
    out.append("    { %s },%s" % (row, label))
out.append("};\n\n} // namespace kernel::dev")
open("include/shitos/font8x16.h", "w").write("\n".join(out) + "\n")
print("wrote include/shitos/font8x16.h", file=sys.stderr)
